name: CI

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch: {}

jobs:
  build-native:
    name: Build Native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          path: ~/.cargo
      - name: Build Native Package
        run: nix build
      - name: Upload Native Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: native-binary
          path: ./result/bin/

  build-armv7:
    name: Build ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          path: ~/.cargo
      - name: Build ARMv7 Package
        run: nix build .#armv7
      - name: Upload ARMv7 Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: armv7-binary
          path: ./result/bin/

  flake:
    name: Flake self-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          path: ~/.cargo
      - name: Commit Check
        run: |
          nix develop --ignore-environment --command ./misc/git-hooks/pre-commit
